### ISSUE TITLE
How to manage your seeds

### ISSUE THREAD

**Issue by pinzonjulian** [rubyaustralia/melbourne-ruby#159]
Hey!
I'd like to see a talk on seed management. It's a critical part to an app and there is very little information on how to create, maintain and scale seeds for an app.

It'd be awesome to see some examples from small, medium and big projects.

Hope someone has the expertise around here to teach us about this :) Thanks!

**Comment by elle** [comment]
I can do a talk about this

**Comment by colquhounking** [comment]
Excellent!
