### ISSUE TITLE
Fixtures vs Factories? When to use each?

### ISSUE THREAD

**Issue by pinzonjulian** [rubyaustralia/melbourne-ruby#168]
This is a topic I haven't been able to wrap my head around when creating a healthy test suite. 

Fixtures seem to have been banned from the internet but I've seen big companies talking about how a combination of both can create a test suite that is both performant and easy to use.

What's the secret? What should be a fixture and what should be a factory?

It'd be awesome to see someone give a talk about this topic

**Comment by map7** [comment]
Here is a blog post which I found which might answer some of these questions (or raise more questions)
https://blog.quantic.edu/2015/01/28/fixturies-the-speed-of-fixtures-and-the-maintainability-of-factories/

**Comment by pinzonjulian** [comment]
Thanks for the post @map7 ! I still have a ton of questions though 😂

**Comment by optimistic-updt** [comment]
@pinzonjulian 
Where do you sit with this these days?
can you now do a talk about it :P

**Comment by pinzonjulian** [comment]
@optimistic-updt Still confused 😂
