### ISSUE TITLE
Talk Proposal: Black hat Ruby - Creating a malicious Ruby Gem

### ISSUE THREAD

**Issue by daveallie** [rubyaustralia/melbourne-ruby#191]
Ruby gives us a lot of sharp knives, but what if someone was to use them not for good, but for evil?
This talk will be an exploration into what malicious Ruby gems can do and how bad actors disguise themselves by looking at some examples and creating one live.

Duration: no idea 😂 I can check back in closer to the meetup date with how deep I'll be going

---

**Disclaimer: Please do not intentionally create malicious gems with the intent to distribute them! This should be treated as an educational piece on why we should all be wary around open-source code.**

**Comment by optimistic-updt** [comment]
Heya Dave,

How long do you reckon your talk would be?
Sounds like a 20-30 min talk to me? Minimum.

I know you were worried about the clash with react meetup.
Would you be possibly able to do it on the 29th instead?

It looks like roro is going to have to move due to room availability

**Comment by daveallie** [comment]
Yeah, 30 minutes would be good. Either the 29th or 30th are both fine, if the clash happens I'll attend RORO

**Comment by optimistic-updt** [comment]
Dave,
I'm going to save you for next year, ok?
Jan 25th.

ok for you?

**Comment by daveallie** [comment]
I'll be up in Brisbane on the 25th of Jan, but will back back down for Feb!

**Comment by optimistic-updt** [comment]
Heya Dave, Would you be keen to present this one this month on the 29th?

**Comment by daveallie** [comment]
Yeah perfect, sounds good!
