### ISSUE TITLE
Awesome GitHub Landing Page

### ISSUE THREAD

**Issue by friendlyantz** [rubyaustralia/melbourne-ruby#192]
Proposing a lightning talk for RORO Melbourne!

- Titile(WIP): Awesome GitHub Profile / Landing Page
- About: how to make your main gitHub profile page look fantastic 🚂 , and perhaps touch on elementary bits of TDD and static website framework used on GitHub(Jekyll) 
- Timing: Nov-2022
- Are you happy to have your talk published on the RubyAU YouTube channel? -> `yes`
- Your Twitter username (if you have one) -> [@friendlyantz](https://twitter.com/friendlyantz)
- Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: 

<img src="https://user-images.githubusercontent.com/70934030/199131724-7f0f0a0f-0a42-4e96-9df7-0f763c3ff2b9.png" alt="drawing" width="200"/>

Talk might be as short as 5mins or as long as 15

**Comment by friendlyantz** [comment]
also, might copy-paste a template for creating new issues from Sydney RoRO

**Comment by optimistic-updt** [comment]
Heya,
Still keen?
Do you think you can do it on the 29th instead of 30th?
It looks like this month roro is going to have to he on the tuesday

**Comment by friendlyantz** [comment]
Absolutely!

**Comment by optimistic-updt** [comment]
Anton, I'm going to save you for next year.
First in Jan 25th.
Can you do that?
I would like to finish the year with two big talks
let me know if ok

**Comment by friendlyantz** [comment]
Yeah, that's no worries at all!

**Comment by friendlyantz** [comment]
Nope, sry, I am away at the moment, coming back to VIC in Feb

**Comment by optimistic-updt** [comment]
Anton, would you be keen to do this one this month or you'd rather do the queuing theory?

**Comment by friendlyantz** [comment]
hey Kevin, I need some time to get queuing theory presso ready. This is ok as a warm-up before / in between main speakers

**Comment by optimistic-updt** [comment]
yes you'd probably go first :)
