### ISSUE TITLE
Talk Proposal: Testing in Production: there is a better way

### ISSUE THREAD

**Issue by igas** [rubyaustralia/melbourne-ruby#193]
A journey on how to do refactoring in mission-critical production code with confidence.

**Comment by optimistic-updt** [comment]
Hey legend,
How long do you reckon this talk would be?
Would upu be good to give it on tuesday the 29th instead of the 30th of November?

**Comment by igas** [comment]
Hey, 40-45 minutes I think. 29th works for me 👍🏼

**Comment by optimistic-updt** [comment]
Let's DO IT.
You re on for next Tuesday 👍🏻

**Comment by igas** [comment]
@optimistic-updt 👍🏼  I updated the title 🙏🏼

**Comment by optimistic-updt** [comment]
@igas 
Are you still G for tomorrow?

Do you have a mugshot I can use?

Cheers
