### ISSUE TITLE
Talk Proposal: Data Encryption in Rails: Why Isn't Everyone Doing It?

### ISSUE THREAD

**Issue by mpalmer** [rubyaustralia/melbourne-ruby#194]
As a number of recent high profile breaches have demonstrated, a lot of our deeply personal information is regularly getting compromised.  Encrypting data is an extremely effective way of protecting that data, but it's still not a universal practice.  It's easy to assume that it's just overworked developers or myopic management, but there are some real challenges to encrypting data that doom many applications to have to store their data in plain text, when they'd really prefer not to.

I'll talk about data encryption and why it's not as widely used as it really should be, and a new open source project I've started to address some of the challenges of usable data encryption, which happens to have an ActiveRecord plugin as its first public client.

Format: I can pare it down to 15 minutes if necessary, but 30-45 minutes gives me a chance to really get the message across.  With more time I can give the pure Rubyists a thrill, too, with more of a deep dive into the underlying technology (such as the joys of tying Ruby and Rust together).

Availability: I can't make it to meetups in the school holidays, so either this coming meetup (Nov) or it'll have to push out to Feb (or later).

**Comment by optimistic-updt** [comment]
This sounds amazing.
Let me see what i can do with current propose talks.
Definitely want to allow the full 45min.
Are you tentatively available 29th of November?
Roro might fall on that day this month due to room availability

**Comment by mpalmer** [comment]
I can do the 29th.

**Comment by optimistic-updt** [comment]
We are on Matt.

Get it ready for next Tuesday :) Let's finish the year big :)

**Comment by mpalmer** [comment]
Roger dodger.  Slide manufacturing is now commencing.

**Comment by optimistic-updt** [comment]
hey @mpalmer,
Are you all good for tomorrow?

Venue is at the dock, are you across that?
Come at 5.50 if you want to test your setup

I need a mugshot from you for my slides

You'll prob go second,
Are you on the Ruby slack? if so under waht name.

Do you have a twitter handle?

**Comment by mpalmer** [comment]
I am ready to rawk for tonight.  I'm aware of the venue change, and will be there early to test my setup.  Will my GitHub profile pic work, or do you need something higher res?  I'm not on the Ruby slack, but my Twitter handle is @tobermatt.

**Comment by optimistic-updt** [comment]
I can roll with that ;) 
see you tonight
