### ISSUE TITLE
Talk Proposal: Roll Your Own Ruby Type Checking Library

### ISSUE THREAD

**Issue by tristanpenman** [rubyaustralia/melbourne-ruby#201]
The idea for this talk stems from a conversation I had with a colleague, about the ways that one could implement Sorbet's type annotations. I've been experimenting with some different techniques, and think it could be interesting material for a talk at the Ruby meetup.

I've already written up some of this as a blog post, using meta-programming to annotate functions. So the talk would be partly based on that, and partly a follow up that explores some of the challenges of type checking in a language as dynamic as Ruby.

Length: 20-30 mins

**Comment by optimistic-updt** [comment]
hey Tristan,

Would you be ok for April meetup?

**Comment by tristanpenman** [comment]
April works well for me.

**Comment by optimistic-updt** [comment]
Done

**Comment by optimistic-updt** [comment]
@tristanpenman, Can I keep you in the back pocket for next week? 😓 
My planned main speaker is currently not answering me...
Let me know if that is an option and I ll aim to confirm by tomorrow.

Cheeers

**Comment by tristanpenman** [comment]
Hey @optimistic-updt, I can make that work 👍

**Comment by optimistic-updt** [comment]
Ok i ll confirm tomorrow.
Cheers

**Comment by optimistic-updt** [comment]
hey @tristanpenman , my other speaker came through, let's schdule you for april as originally arranged

**Comment by tristanpenman** [comment]
All good 👍

**Comment by optimistic-updt** [comment]
Hey @tristanpenman , still good to do it this week?
Can you possibly do it on the Thursday? I might have to move the meetup to Thursday as I'm having problem securing a room.

Cheers

**Comment by tristanpenman** [comment]
No worries. Content is all good to go, and either Wednesday or Thursday are okay for me.

**Comment by tristanpenman** [comment]
Hi @optimistic-updt is this going ahead tonight (Wednesday) or moving to Thursday?

**Comment by optimistic-updt** [comment]
hi Tristan,
Despite best effort to reschedule this week or on the same day.
My only earliest possibiliy is next Friday 5th of May.

Would you still be able to attend and speak?

Sorry about the mess around

**Comment by tristanpenman** [comment]
Totally understand the challenges with meetup admin, having been in that spot a few times myself 😬

5th of May works for me, so I'll keep that free in my calendar.

**Comment by optimistic-updt** [comment]
Let's lock it in 🔥
