### ISSUE TITLE
The State of OpenTelemetry for Ruby Developers 

### ISSUE THREAD

**Issue by friendlyantz** [rubyaustralia/melbourne-ruby#202]
Proposing a lightning/mid talk for RORO Melbourne

__Title:__ OpenTelemetry 
__About:__ my takeaways from toying with OpenTelemetry, and how it compares to DataDog, etc

__Timing:__ mid-2023

>    Are you happy to have your talk published on the RubyAU YouTube channel? -> yes
    Your Twitter username (if you have one) -> [@friendlyantz](https://twitter.com/friendlyantz)
    Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: refer https://github.com/rubyaustralia/melbourne-ruby/issues/192

__Timing:__ 10-20mins

**Comment by simran-sawhney** [comment]
Hey @friendlyantz - this is so cool and will be helpful for alot of devs in community. let's do it for June 28th ?

**Comment by friendlyantz** [comment]
Hey @simran-sawhney, let me see what I can prepare... unless we have other volunteers/talk, I can slap something together

**Comment by simran-sawhney** [comment]
Hey @friendlyantz - I was bit away from system but yeh let me confirm you in a day or 2, as we always are looking for new ones. But hey, now we know we have solid talk coming up anyways, so yeh let's be on stand by. I would try to encourage new speakers and see if we can find something.

**Comment by friendlyantz** [comment]
No worries, will put on hold. Keep me posted

**Comment by simran-sawhney** [comment]
Alright @friendlyantz - let's rock and roll this one, maybe it's meant for you this time mate. I think most of the speakers are quite busy shopping these days lol so not 100% confirmations coming through.

let me know if you are good with this so we can book this one in.

**Comment by simran-sawhney** [comment]
Hey @friendlyantz - can we lock this in then so I can attach this through the event details ?
Cheers,
