### ISSUE TITLE
Running ruby in browser using web assembly

### ISSUE THREAD

**Issue by prgrmr-yn** [rubyaustralia/melbourne-ruby#204]
We will be using ruby to handle events on DOM

Title: 
About: how to integrate a hardware key (i.e. YubiKey) into ssh

Timing: ready_now

Are you happy to have your talk published on the RubyAU YouTube channel? -> yes
Your Twitter username (if you have one) -> @prgrmr-yn 
Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: 
Timing: 10 mins

**Comment by optimistic-updt** [comment]
hey @prgrmr-yn , Happy to this at the may meetup in a couple of weeks?

**Comment by optimistic-updt** [comment]
hey @prgrmr-yn, do you wnat to do this talk next week?

**Comment by prgrmr-yn** [comment]
> hey @prgrmr-yn, do you wnat to do this talk next week?
> 
> 

Not anymore sorry
