### ISSUE TITLE
recent ruby conferences

### ISSUE THREAD

**Issue by saramic** [rubyaustralia/melbourne-ruby#205]
I have had the opportunity to attend a heap of recent ruby related conferences. In this talks I will share:

1. what I have learnt
2. how I got to go
3. upcoming conferences
4. how to get the most out of conferences

the conferences covered are:

1. RubyConfTH Bangkok 2022
2. RubyConfAU Melbourne 2023
3. Programmable Melbourne/Sydney 2023
4. TestBash Spring London | Remote 2023
5. ReactMiami 2023
6. RailsConf Atlanta 2023
7. RubyKaigi Matsumoto 2023
8. and coming soon CPP Canada, RustConf Albuquerque, ReactSummit Amsterdam | Remote, NDC Copenhagen

talk will be anywhere from 10min - 40min and include some audience interaction and games if we go for the longer version

talk slides will be here -> https://github.com/failure-driven/conferences-2023

**Comment by simran-sawhney** [comment]
@saramic - let's do it :)
