### ISSUE TITLE
The commit narrative: Penning the chronicles of your code

### ISSUE THREAD

**Issue by HashNotAdam** [rubyaustralia/melbourne-ruby#206]
Description(this will appear on youtube):
Unveil the compelling story hidden in your code. This talk redefines the role of commit messages in software development, urging us to look beyond the 'what' and delve into the 'why' behind each code change. Through a blend of industry anecdotes, practical guidelines, and hands-on examples, we unravel how insightful commit messages foster better collaboration, streamline debugging, and guide new team members on their journey through your project's history.

Estimated Talk Time:
10–15 min

Prefered Month to Present:
May

Preferred Social media handles:
HashNotAdam

Mugshot (will be use in the slides):
https://www.hashnotadam.com/Adam%20Rice.jpg

**Comment by simran-sawhney** [comment]
Let's do it @HashNotAdam for tomorrow

**Comment by HashNotAdam** [comment]
> Let's do it @HashNotAdam for 31 May

Look forward to seeing you then 😄
