### ISSUE TITLE
Tabs vs Spaces - Developer smackdown lightning talk

### ISSUE THREAD

**Issue by saramic** [rubyaustralia/melbourne-ruby#207]
@SelenaSmall and @saramic (Michael Milewski) what to demo and test a part of their interactive **Developer Smackdown** talk, as will be featured at [NDC Copenhagen Aug 30](https://cphdevfest.com/agenda/developer-smackdown-015a/051ortmnqer).

We want to share a ⚡️ **7 minute** _almost_ lightning talk ⚡️ version with a few of our closest friends at the RORO meetup. We are hoping for everyone to pull out a device and interact with our presentation to find out the true answers to key developer questions like:

* are **Tabs** better than **Spaces** ?
* are **Monoliths** better than **Microservices** ?
* is **Pairing** better than **Soloing** ?
* are **Branches** better than **Pushing to Trunk** ?

ready to go for Wed 28th June

**Comment by simran-sawhney** [comment]
Let's do it :)
