### ISSUE TITLE
Talk Proposal: How FHIR is tackling a wicked problem with technical, social and political solutions

### ISSUE THREAD

**Issue by MattHood** [rubyaustralia/melbourne-ruby#209]
Description (this will appear on YouTube): 

The project of interoperability in healthcare is one that would make healthcare workers' jobs easier, our healthcare industry more efficient, and improve our experiences as patients. Yet, in spite of these upsides, the project has been held back by technical difficulty, a lack of cooperation and misaligned incentives. 

One of the most promising developments in this space is HL7's FHIR standard, an extensible meta-model for exchanging healthcare data. Not only does FHIR offer some novel and fascinating techniques for flexibly modelling a wide range of data, it also engages in the community-building required to help it solve real problems, and the advocacy which is seeing it gain acceptance and mandate in national and international politics.

This talk will examine how Ruby developers can make productive use of FHIR in their projects, by describing the design of FHIR and the state of the tooling available to the Ruby ecosystem. Also discussed will be the lessons we can learn from FHIR on community-building and advocacy for our own technology solutions.

Estimated Talk Time: 20 minutes

Preferred Month to Present: July '23

Preferred Social Media Handles: matthood0@gmail.com

Mugshot (will be used in the slides):
![mattbio](https://github.com/rubyaustralia/melbourne-ruby/assets/1885706/ebc7dec6-6fb4-4042-968e-b860ed8ef3f7)

**Comment by simran-sawhney** [comment]
hey @MattHood we have added milestone for this issue July talk, see you then!
