### ISSUE TITLE
O(n) - BigO complexity of a Job Interview Algorithm

### ISSUE THREAD

**Issue by friendlyantz** [rubyaustralia/melbourne-ruby#211]
Proposing a lightning/mid talk for RORO Melbourne

__Title:__ BigO explained with examples
__About:__ I found that a lot of companies still test your knowledge of algorithms and BigO complexity. Many will argue that these knowledge is uselees and not really required to `center a <div>`. However, it seems to be a 'secret' handshake you need to learn if you want to apply to a corporate company and be successfull at your dream job at FacePalm, Hooli, etc [aligning buttons and doing colour animations](https://www.twitch.tv/j_blow/clip/UninterestedAuspiciousPizzaFreakinStinkin-4Urg8_phIw1jbHme).
I will present my takeaways and tips how to quickly estimate it. (I used [ThePrrimeagen's Aglorithm Course](https://frontendmasters.com/courses/algorithms))

- BigO what it is; Time and Space; O(1), O(n), logn, n logn, n^2, n!, etc
- how to roughly estimate it
- examples of different algorithms and BigO estimation

__Timing:__ tbc

>    Are you happy to have your talk published on the RubyAU YouTube channel? -> yes
    Your Twitter username (if you have one) -> [@friendlyantz](https://twitter.com/friendlyantz)
    Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: refer https://github.com/rubyaustralia/melbourne-ruby/issues/192

(can be 10-15mins or as long as 30mins)

**Comment by optimistic-updt** [comment]
👍🏻  Let's look at doing this in the last quarter maybe
