### ISSUE TITLE
Talk Proposal: But why does it work?

### ISSUE THREAD

**Issue by rianmcguire** [rubyaustralia/melbourne-ruby#212]
Description(this will appear on youtube): Nothing is a black box! Get the confidence to dive into unfamiliar code and languages, and understand how things really work. Join me on a deep dive into gems, the Ruby source code (and maybe more!)

Estimated Talk Time: 15-30 min

Preferred Month to Present: July 😱

Preferred Social media handles: None

Mugshot (will be use in the slides): https://avatars.githubusercontent.com/u/1201065

**Comment by simran-sawhney** [comment]
hey @rianmcguire - thanks for raising the issue mate. are you okay to do it in August if you need more time to prep, this way we would have locked in for next month ?

**Comment by simran-sawhney** [comment]
hey @rianmcguire moving this to next month mate for August one - let's lock that in :)

**Comment by simran-sawhney** [comment]
Hey @rianmcguire - let's do it mate this month. I have added Milestone to it already :)
