### ISSUE TITLE
Proposal: a production bug 27 years in the making

### ISSUE THREAD

**Issue by radar** [rubyaustralia/melbourne-ruby#213]
The most robustly tested application at the company. A PR to upgrade Ruby, weeks in the The tests passed on local and on CI. No issues detected on staging or the sandbox environment. All systems green.

Then the production deploy started.

---

A time-traveling tale of how a confluence of changes came together to cause an issue in production.

Duration: 10-15 minutes
Month: July 2023

**Comment by simran-sawhney** [comment]
Let's do this next week on 26th July meetup!

**Comment by radar** [comment]
Looking forward to it!
