### ISSUE TITLE
Dragonruby: Creating the game "Metal Warrior: Search for Valhalla"

### ISSUE THREAD

**Issue by map7** [rubyaustralia/melbourne-ruby#215]
A lightening talk proposal (5mins) just going over some of the highlights and issues we had whilst creating a 2d action game called "Metal Warrior: Search for Valhalla".

**Comment by map7** [comment]
Timed the talk last night, could go up to 10min, we'll see. I had a rough crowd to practice in front of (my kids)

**Comment by ponny** [comment]
Super keen for this!
