### ISSUE TITLE
[discussion]: Rails architecture with engines work group

### ISSUE THREAD

**Issue by antulik** [rubyaustralia/melbourne-ruby#218]
I'll demo an app and talk about my experience for a little bit. The goal is to have an audience discussion and share experiences about using rails engines. Other people are welcome to demo their examples as well.

Length: 1-1.5 hour discussion

**Comment by optimistic-updt** [comment]
that sounds awesome,
Let's maybe have it in november ❤️

**Comment by optimistic-updt** [comment]
are you stil happy to this next week?

**Comment by antulik** [comment]
yes
