### ISSUE TITLE
Something Something Fibers Something

### ISSUE THREAD

**Issue by KJTsanaktsidis** [rubyaustralia/melbourne-ruby#222]
Yes, the title of the talk is "Something Something Fibers Something" - I'll try and nail down more specifically what I want to talk about this weekend :)

I'd like to do a talk that really gets into the low-level guts of how fibers work in Ruby. The rough kind of thing I'm thinking of covering is...

* What a Fiber is, and how fibers relate to threads
* How Fiber.yield/Fiber.resume work in Ruby
* What you can build with them (e.g. implementing enumerators with them, "saving" the context of being inside a block)
* How the Ruby and C call stacks relate to each other (this is important prerequisite info which is kind of genuinely interesting on its own)
* How Fiber.yield and Fiber.resume are implemented in terms of the C call stack

I would also like to talk about Fiber.transfer & the new Ruby fiber scheduler interface & the async gem, but let's see how much content ☝️  turns out to be. Maybe it's a different talk for another time.

I'll be able to present this on Jan 25.

**Comment by ZimbiX** [comment]
Very cool. I've been keen for a talk like this since Ruby 3 came out :grin:

**Comment by simran-sawhney** [comment]
Thanks for the great talk @KJTsanaktsidis
