### ISSUE TITLE
Processing DMARC reports via Action Mailbox

### ISSUE THREAD

**Issue by HashNotAdam** [rubyaustralia/melbourne-ruby#223]
Domain-based Message Authentication, Reporting, and Conformance (or DMARC) is an email validation system that builds upon Sender Policy Framework (SPF) and DomainKeys Identified Mail (DKIM) to protect email domains from being used in email spoofing, phishing scams, and other cybercrime.

When creating a DMARC DNS record, you can include a `rua` attribute, the value of which is an email address that servers can send a daily report of the deliverability of emails from your domain. This provides valuable data that can help you check that you've approved every server that you expect to be able to send on your behalf and reduce the number of legitimate emails that are sent to spam. Unfortunately, these reports come as XML files which are usually GZipped which makes them poorly suited to human reading. Also, since they are sent by the receiving servers, you can expect to be sent many reports per day.

This talk is the story of how I leveraged Action Mailbox in Ruby on Rails to automatically parse incoming DMARC reports and alert me to issues in a human-readable format.

**Comment by simran-sawhney** [comment]
Thanks for the great talk @HashNotAdam
