### ISSUE TITLE
Talk Proposal : System Design & Distributed System Lightweight Concept

### ISSUE THREAD

**Issue by Stefanuswilfrid** [rubyaustralia/melbourne-ruby#224]
- What to do when our app gains popularity (Vertical & Horizontal Scaling)
- Horizontal scaling best practices (instance stickiness, louse coupling ) 
-  Distributed Systems ( stuff like chaos monkeys, retry mechanism should be somewhat fun )
- Could also talk abt some tools like kubernetes ( just the lightweight stuff like k8 backgrounds, pods, deleting pods , scalling , and a bit abt writing .yaml file not the advanced or super detailed ) .

**Comment by simran-sawhney** [comment]
hey @Stefanuswilfrid - . It's a great topic but for it to be qualified for lightning talk, this seems bit too heavy. Is there any chance if you could decrease the presentation and talk time to 10 minutes maximum and realign the details in your slides accordingly ?

**Comment by ZimbiX** [comment]
Or have it be a full talk?

**Comment by Stefanuswilfrid** [comment]
hey , ur right i think for the lightning talk i'l just talk abt 'scaling you app 101' . in the bginning i thought i was supposed to propose about topics for multiple weeks lol.

**Comment by simran-sawhney** [comment]
Thanks for the talk @Stefanuswilfrid !
