### ISSUE TITLE
Can I host a rails app from a home server?

### ISSUE THREAD

**Issue by saramic** [rubyaustralia/melbourne-ruby#226]
With the advent of cloud and the availability of PaaS (Platform as a Service) providers like Heroku, Fly.io, Render, and Hatchbox, why would even consider running a **rails app** on **bare metal** from home?
- because you can?
- because it's cheaper?
- because you want to be your own sysadmin/devops?
- because you want the internet to be back like it was in **1999 🎉 !!!**
- because there has been some recent noise on this in the Rails community
    **[RECLAIM THE STACK!](https://reclaim-the-stack.com/)**
    > We spent 7 months building a Kubernetes based platform to replace Heroku. The results were a 90% reduction in costs and a 30% improvement in performance.
    
    **[KAMAL](https://kamal-deploy.org/)** _formerly MRSK_
    > Leaving the cloud will save us $7 million over five years.
    https://basecamp.com/cloud-exit
- because @friendlyantz - wants to know
    [Ruby Australia Slack #melb-meets 3:27pm Oct 5 2023](https://rubyau.slack.com/archives/C010RUGPRHU/p1696480053027199?thread_ts=1696479747.231869&cid=C010RUGPRHU)
  > Keen to hear about these topics(hope it inspires someone):
  >  * Self hosting ruby app

So **"can I host a rails app from a home server?"** whats involved? how hard can it be? is it just `RAILS_ENV=production bin/rails server`?

let's see how far I can get - maybe a **5 minute talk** or maybe **30 minutes** depending how far I get

NOTE: _this is part of a larger talk idea for running a rails app locally on **bare metal** using a laptop, moving it into the **cloud☁️** and back again on-premise on **bare metal** home cluster_

**Comment by simran-sawhney** [comment]
Thanks for the great talk @saramic !
