### ISSUE TITLE
The Economics of Ruby

### ISSUE THREAD

**Issue by ponny** [rubyaustralia/melbourne-ruby#227]
Description(this will appear on youtube):
John is a developer that likes both Ruby and Economics.  

This is a lightning talk about the flow of resources and incentives in the Ruby ecosystem.  It will discuss the costs of maintaining Ruby, the support from various benefactors/companies, and the contributors that make it all happen.

Estimated Talk Time: 10 minutes

Prefered Month to Present: March 2024

Preferred Social media handles: 
https://twitter.com/ponny

Mugshot (will be use in the slides): just use my github avatar

**Comment by simran-sawhney** [comment]
Thanks @ponny - let's do this on 28th March!

**Comment by simran-sawhney** [comment]
Thanks @ponny for your amazing talk!

**Comment by ponny** [comment]
@simran-sawhney No worries.  A couple of people asked for the vid so could you please post it here when it's up?

**Comment by simran-sawhney** [comment]
@ponny here is the posted video link!
https://www.youtube.com/watch?v=ydU3WvLoXpY
