### ISSUE TITLE
One Billion Rows in Ruby

### ISSUE THREAD

**Issue by rianmcguire** [rubyaustralia/melbourne-ruby#228]
Description(this will appear on youtube):
Is Ruby a good language for CPU-intensive data crunching? Can it beat Java? This talk is about my adventures taking on the One Billion Row Challenge (https://github.com/gunnarmorling/1brc) in Ruby. I'll cover some of the tools, techniques and pitfalls around optimising Ruby programs.

Estimated Talk Time: maybe 30 minutes? (haven't timed it yet)

Preferred Month to Present: March 2024

Preferred Social media handles: None

Mugshot (will be use in the slides): https://avatars.githubusercontent.com/u/1201065

**Comment by simran-sawhney** [comment]
Thanks @rianmcguire - let's do it on 28th March!

**Comment by simran-sawhney** [comment]
Thanks @rianmcguire for your amazing talk!
