### ISSUE TITLE
Dissecting Rails

### ISSUE THREAD

**Issue by friendlyantz** [rubyaustralia/melbourne-ruby#229]
Lightning talk for RORO Melbourne

__Title:__ Dissecting Rails 
__About:__ How I learn Rails. My takeaways from dissecting Rails: Active Support, Active Model, etc

__Timing:__ APR-2024

>    Are you happy to have your talk published on the RubyAU YouTube channel? -> yes
    Your Twitter username (if you have one) -> [@friendlyantz](https://twitter.com/friendlyantz)
    Link to, or upload of, a photo of yourself that will appear in the meetup slide deck: refer https://github.com/rubyaustralia/melbourne-ruby/issues/192

Length: 10-15min

**Comment by simran-sawhney** [comment]
Thanks @friendlyantz for your insightful talk :)
