### ISSUE TITLE
Talk Proposal: One does not simply... rebuild a product

### ISSUE THREAD

**Issue by itirkarp** [rubyaustralia/melbourne-ruby#232]
Description(this will appear on youtube): 

"A rebuild is never finished, only started"

We're rebuilding Culture Amp's second largest product - Performance. It's 9 years old, came in as a Series A acquisition 5 years ago, has over 2700 customers with the largest one at 77k users. Against conventional wisdom, we're rebuilding it from the ground up with an aggressive timeline. The underlying model is outdated, slow to iterate on, and not extensible. The monoliths are riddled with tech debt, tightly coupled, patched and band-aided over many times, and won't scale to the $3b global Performance market we're targeting.

That wasn't challenging enough already so I'm also using this opportunity to rebuild our engineering culture. Setting a high bar for engineering standards, ways of working, and hoping to improve engagement as we go.

In this talk, I'll share:

- How I came to this decision
- How we got buy in from Exec and the Board for a purely technical rebuild
- How we tried to set up for success, our principles and standards
- Where we failed
- Where we succeeded
- Lessons that could be useful for anyone thinking about rebuilding a product that's hampering speed and hindering your ability to innovate or deliver value to your customers.

The rebuild is still in progress. I don't have all the answers (or any!). But we've already learned much - what to do, what not to do, and where the spiders are hiding.

Estimated Talk Time: 35 - 40 minutes

Preferred Month to Present: June

Preferred Social media handles: https://www.linkedin.com/in/prakritimateti/

Mugshot (will be use in the slides): [link to photo](https://github.com/rubyaustralia/melbourne-ruby/assets/502956/6fd7dfe4-5f49-4c48-bccd-8784e41e48b7)

**Comment by simran-sawhney** [comment]
Thanks @itirkarp - let's do it this month on 27th June
