### ISSUE TITLE
Talk Proposal: Being a Good Male Ally

### ISSUE THREAD

**Issue by quintrino** [rubyaustralia/melbourne-ruby#233]
Description(this will appear on youtube):
Being a Good Male Ally

Estimated Talk Time:
15-20 minutes. 
Prefered Month to Present:
May
Preferred Social media handles:
https://nickwolf.com.au

**Comment by simran-sawhney** [comment]
hey @quintrino - do you wanna do this on 25th July - Thursday?

**Comment by quintrino** [comment]
Sounds good to me.

**Comment by simran-sawhney** [comment]
Thanks for the amazing talk!
