### ISSUE TITLE
Talk Proposal: Pinkest Pink

### ISSUE THREAD

**Issue by danlaush** [rubyaustralia/melbourne-ruby#235]
Description:
Did you know the web got new colors? The pink is pinker than it used to be. The colors are so bright and we can use them on web pages. I'm not an expert in this space but I am excited to share what I've learned about the topic, like how our eyes work and how we try to recreate reality on a screen.

Estimated Talk Time: 10 or 20min, can probably scope it to a lightning talk if it's better for timing

Prefered Month to Present: No preference, can do with short notice if needed

Preferred Social media handles: `@danlaush`, https://danlaush.biz/

Mugshot (will be use in the slides):
https://github.com/rubyaustralia/melbourne-ruby/assets/1204500/da13da31-84bb-4e52-baa5-372a7f304195

**Comment by simran-sawhney** [comment]
hey @danlaush - do you wanna do this for this month at 25th July?

**Comment by danlaush** [comment]
Hey Simran, sure I'd be happy to. It's pretty solid with a 15min run time, does that work?

**Comment by simran-sawhney** [comment]
Hey @danlaush yep that will work fine. Let's do it mate on 25th July (Thursday)
Here is the event details. https://www.meetup.com/ruby-on-rails-oceania-melbourne/events/297781282/

**Comment by simran-sawhney** [comment]
Hey @danlaush - could you please confirm it so I can lock it in for the event?
Thanks mate,

**Comment by danlaush** [comment]
Oh whoops I didn't submit what I wrote earlier! Yes I'm in, thanks for accepting and looking forward to it.

**Comment by danlaush** [comment]
@simran-sawhney do you need a PDF/document for the talk or will I be able to plug my laptop in?

**Comment by simran-sawhney** [comment]
Sorry I just saw your comment now, thanks for the amazing talk last night!
