### ISSUE TITLE
Talk Proposal: Rails Engines in 20 minutes

### ISSUE THREAD

**Issue by excid3** [rubyaustralia/melbourne-ruby#237]
Description(this will appear on youtube):
In this talk, we'll walk through building a basic Rails plugin and talk about the different ways of extending Rails through Engines.

Estimated Talk Time: 
20mins

Prefered Month to Present: 
August

Preferred Social media handles: 
@excid3

Mugshot (will be use in the slides):
https://rubyonrails.org/assets/world/2023/images/speakers/c-oliver.jpg

**Comment by simran-sawhney** [comment]
Thanks @excid3 - community would be so proud and excited to hear it from you !!!🔥
