### ISSUE TITLE
Talk Proposal: Happy Ruby SAML Development

### ISSUE THREAD

**Issue by pat** [rubyaustralia/melbourne-ruby#239]
**Description (this will appear on YouTube):**

This talk is an introduction to how SAML requests and responses can be handled with Ruby, as well as a discussion around how we at [Covidence](https://www.covidence.org) have solved such challenges as:

* Building SAML support ourselves rather than using third-party services.
* Writing full feature tests to sign in via SSO (no mocking of SAML objects/responses).
* Bridging SAML requests across many domains for staging/PR apps, to ensure a consistent approach across environments.
* Parsing SAML metadata files using Nokogiri for better performance.

**Estimated Talk Time:**

20-30 minutes

**Preferred Month to Present:**

October or November 2024 (I'm away prior to that, sorry!)

**Preferred Social media handles:**

https://hachyderm.io/@pat

**Mugshot (will be use in the slides):**

![](https://media.hachyderm.io/accounts/avatars/109/308/312/683/593/994/original/49c39d379fbc3d37.jpg)
[https://media.hachyderm.io/accounts/avatars/109/308/312/683/593/994/original/49c39d379fbc3d37.jpg](https://media.hachyderm.io/accounts/avatars/109/308/312/683/593/994/original/49c39d379fbc3d37.jpg)

**Comment by simran-sawhney** [comment]
Hey @pat do you wanna go for it this month on 24th Oct ?

**Comment by pat** [comment]
@simran-sawhney yup, let's lock it in 😁
