### ISSUE TITLE
Talk Proposal: Oaken - A fresh take on seeds and fixtures

### ISSUE THREAD

**Issue by pinzonjulian** [rubyaustralia/melbourne-ruby#240]
Description(this will appear on youtube): Exploring Oaken - A fresh take on seeds and fixtures

Estimated Talk Time: 30min

Prefered Month to Present: September 

Preferred Social media handles: pinzonjulian everywhere

Mugshot (will be use in the slides): TBD

**Comment by pinzonjulian** [comment]
This addresses two past issues I posed a while ago for talks I wanted to see!

**Comment by HashNotAdam** [comment]
You have my attention with that title 😃

**Comment by HashNotAdam** [comment]
@pinzonjulian I've used the photo from GitHub, but you're welcome to supply another

**Comment by simran-sawhney** [comment]
Thanks @pinzonjulian, it was a great talk!
