### ISSUE TITLE
Requested Talk: How does `reload!` work?

### ISSUE THREAD

**Issue by HashNotAdam** [rubyaustralia/melbourne-ruby#241]
**Description:**
When using the Rails console, you can call `reload!` to reset the environment.
How does this work?
How does it know which classes to reload?
How does a class get reloaded?
What are the implications for intializers?

**Estimated Talk Time:**
10–15 minutes

**Comment by darkfishy** [comment]
@HashNotAdam and @simran-sawhney I can present on this topic at the next meeting.

**Comment by HashNotAdam** [comment]
Thanks so much, @darkfishy, that's a big help. Would you might filling out the following?

Description(this will appear on youtube):

Preferred Social media handles:

Mugshot (will be use in the slides):

**Comment by darkfishy** [comment]
Hey @HashNotAdam 

> Description(this will appear on youtube):

Same as above in https://github.com/rubyaustralia/melbourne-ruby/issues/241#issue-2537778854

> Preferred Social media handles:

https://x.com/fusionfish

> Mugshot (will be use in the slides):

Supplied to @simran-sawhney

**Comment by simran-sawhney** [comment]
Thanks @darkfishy for putting it all together :)
