### ISSUE TITLE
Requested Talk: Getting started with Cursor

### ISSUE THREAD

**Issue by HashNotAdam** [rubyaustralia/melbourne-ruby#243]
**Description:**
[Cursor](https://www.cursor.com/) is so hot right now. People rave that it far exceeds the competition (e.g. GitHub Copilot). I would love to see a walkthrough [Cursor](https://www.cursor.com/), how to configure it, which AI model to use, and a look at the pros and cons of [Cursor](https://www.cursor.com/) compared to GitHub Copilot.

**Estimated Talk Time:**
10–15 minutes

**Comment by ceels** [comment]
Hey Adam and Simran, I’d like to do this talk in October

**Comment by HashNotAdam** [comment]
Replaced by #245
