### ISSUE TITLE
Talk Proposal:  'Cursor v Github Copilot: building a better data schema tool?'

### ISSUE THREAD

**Issue by ceels** [rubyaustralia/melbourne-ruby#245]
Description:
An evaluation of [Cursor](https://www.cursor.com/), how to configure it, which AI model to use, and a look at the pros and cons of [Cursor](https://www.cursor.com/) compared to GitHub Copilot.

Estimated Talk Time:
10–15 minutes

Prefered Month to Present: October

Preferred Social media handles: @ceels

Mugshot (will be use in the slides): lemme find one real quick
![image](https://github.com/user-attachments/assets/e44e1475-2a29-48a3-ab50-636d63f06f63)

**Comment by HashNotAdam** [comment]
Thanks, @ceels, I can't wait to watch
